# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1590a87b5bcbc4911e40c54ab0cec850eeb130161b3c91bf5f357809924efb4dc27ab6e5f3c0e53c79f1aadd2ec3c826efeec8712d2b2af69efb03062b32e8dc

test:
  secret_key_base: 1f277255896558f4d4c984854f50fd8c9d615b4dc750b067d81cb092e453580eb69ba196dfb47cf3259f89f4396908c222b34d989b7b1437f5d930067f3ab892

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
